image:
  file: .gitpod.Dockerfile

# tasks:
#   - name: LaTeX auto-rebuild
#     command: >
#       while find . -name '*.tex' | xargs inotifywait -qqre modify .; do \
#         latexmk -pdf ; \
#       done
#   - name: Terminal
#
vscode:
  extensions:
    # - efoerster.texlab
    - golang.Go
    - James-Yu.latex-workshop
    # - tomoki1207.pdf
